###
POST http://localhost:5050/api/llm/analyze
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNWFjODI0ZS05M2I5LTRhZDAtOTgxNC1jNDAxZjk0ZGI1NzEiLCJlbWFpbCI6Imxlbmh1dGR1eUBnbWFpbC5jb20iLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc2NTYxNDEyMSwiZXhwIjoxNzY1NjE3NzIxfQ.mufuTL6im5cgS0HjgFc6xuzTUMR4oGd_Ve2sntbffjw
Content-Type: application/json

{
    "question": "Tôi cần 5 sv, pin và khoan"
}